In [40]:
# importing utility modules
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# importing machine learning models for prediction
from sklearn.ensemble import RandomForestRegressor
#import xgboost as xgb
from sklearn.linear_model import LinearRegression
import numpy as np

In [74]:
df=pd.read_csv("iris")
display(df)
df_arr = df.to_numpy()

df=pd.DataFrame(df_arr,columns=['A','sepal_length','sepal_width','petal_length','petal_width','target'])
df.drop('A',axis=1,inplace=True)
display(df)
df["target"].unique()

     Unnamed: 0  5.1  3.5  1.4  0.2     Iris-setosa
0             0  4.9  3.0  1.4  0.2     Iris-setosa
1             1  4.7  3.2  1.3  0.2     Iris-setosa
2             2  4.6  3.1  1.5  0.2     Iris-setosa
3             3  5.0  3.6  1.4  0.2     Iris-setosa
4             4  5.4  3.9  1.7  0.4     Iris-setosa
..          ...  ...  ...  ...  ...             ...
144         144  6.7  3.0  5.2  2.3  Iris-virginica
145         145  6.3  2.5  5.0  1.9  Iris-virginica
146         146  6.5  3.0  5.2  2.0  Iris-virginica
147         147  6.2  3.4  5.4  2.3  Iris-virginica
148         148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 6 columns]

    sepal_length sepal_width petal_length petal_width          target
0            4.9         3.0          1.4         0.2     Iris-setosa
1            4.7         3.2          1.3         0.2     Iris-setosa
2            4.6         3.1          1.5         0.2     Iris-setosa
3            5.0         3.6          1.4         0.2     Iris-setosa
4            5.4         3.9          1.7         0.4     Iris-setosa
..           ...         ...          ...         ...             ...
144          6.7         3.0          5.2         2.3  Iris-virginica
145          6.3         2.5          5.0         1.9  Iris-virginica
146          6.5         3.0          5.2         2.0  Iris-virginica
147          6.2         3.4          5.4         2.3  Iris-virginica
148          5.9         3.0          5.1         1.8  Iris-virginica

[149 rows x 5 columns]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [78]:
mapping={"Iris-setosa":0,"Iris-virginica":1,"Iris-versicolor":2}
df["target"]=df["target"].map(mapping)
display(df)

    sepal_length sepal_width petal_length petal_width  target
0            4.9         3.0          1.4         0.2       0
1            4.7         3.2          1.3         0.2       0
2            4.6         3.1          1.5         0.2       0
3            5.0         3.6          1.4         0.2       0
4            5.4         3.9          1.7         0.4       0
..           ...         ...          ...         ...     ...
144          6.7         3.0          5.2         2.3       1
145          6.3         2.5          5.0         1.9       1
146          6.5         3.0          5.2         2.0       1
147          6.2         3.4          5.4         2.3       1
148          5.9         3.0          5.1         1.8       1

[149 rows x 5 columns]

In [79]:
target = df["target"]

# getting train data from the dataframe
train = df.drop("target",axis=1)

# Splitting between train data into training and validation dataset
X_train, X_test, y_train, y_test = train_test_split(
	train, target, test_size=0.20)

In [80]:
# initializing all the model objects with default parameters
model_1 = LinearRegression()
#model_2 = xgb.XGBRegressor()
model_3 = RandomForestRegressor()

# training all the model on the training dataset
model_1.fit(X_train, y_train)
#model_2.fit(X_train, y_target)
model_3.fit(X_train, y_train)

# predicting the output on the validation dataset
pred_1 = model_1.predict(X_test)
#pred_2 = model_2.predict(X_test)
pred_3 = model_3.predict(X_test)

# final prediction after averaging on the prediction of all 3 models
pred_final = (pred_1+pred_3)/2.0

# printing the mean squared error between real value and predicted value
print(mean_squared_error(y_test, pred_final))

0.0769995061396007